name: CI

on:
  push:
    branches: [main]

jobs:
  sync:
    if: "!contains(github.event.head_commit.message, '[sync-bot]')"

    uses: nandbox-bot/shared-ci/.github/workflows/build-ghcr.yml@main
